/**
 * Code generation for CLI commands using ts-morph for type-safe AST generation
 */

import type { JSONSchema7 } from "json-schema";
import { Project, VariableDeclarationKind } from "ts-morph";
import {
	getSchemaProperties,
	getSchemaTypeHint,
	isArraySchema,
	isObjectSchema,
} from "./introspect.js";
import type { ProcedureInfo, SchemaProperty } from "./types.js";


type CommandNode =
	| { type: "leaf"; procedure: ProcedureInfo }
	| { type: "branch"; children: Map<string, CommandNode> };

const buildCommandTree = (
	procedures: ProcedureInfo[],
): Map<string, CommandNode> => {
	const root = new Map<string, CommandNode>();

	for (const proc of procedures) {
		const segments = proc.path.split(".");
		let current = root;

		for (let i = 0; i < segments.length; i++) {
			const segment = segments[i];
			const isLast = i === segments.length - 1;

			if (isLast) {
				// Leaf node - the actual procedure
				current.set(segment, { type: "leaf", procedure: proc });
			} else {
				// Branch node - a command group
				if (!current.has(segment)) {
					current.set(segment, { type: "branch", children: new Map() });
				}

				// biome-ignore lint/style/noNonNullAssertion: Value is inserted above
				const node = current.get(segment)!;
				if (node.type === "branch") {
					current = node.children;
				}
			}
		}
	}

	return root;
};

const generateOptionExpression = (
	key: string,
	prop: SchemaProperty,
): string => {
	const type = Array.isArray(prop.schema.type)
		? prop.schema.type[0]
		: prop.schema.type;
	const description = prop.schema.description || getSchemaTypeHint(prop.schema);

	let base: string;

	if (type === "number" || type === "integer") {
		base = `number("${key}").desc("${description}")`;
	} else if (type === "boolean") {
		base = `boolean("${key}").desc("${description}")`;
	} else if (prop.schema.enum && Array.isArray(prop.schema.enum)) {
		const enumValues = prop.schema.enum.map((v) => `"${v}"`).join(", ");
		base = `string("${key}").desc("${description}").enum(${enumValues})`;
	} else {
		base = `string("${key}").desc("${description}")`;
	}

	if (prop.defaultValue !== undefined) {
		if (type === "number" || type === "integer") {
			return `${base}.default(${Number(prop.defaultValue)})`;
		} else if (type === "boolean") {
			return `${base}.default(${prop.defaultValue === true})`;
		} else {
			// strings and enums
			return `${base}.default("${String(prop.defaultValue)}")`;
		}
	}

	if (prop.required) {
		return `${base}.required()`;
	}

	return base;
};


const generateOptionsObject = (properties: SchemaProperty[]): string => {
	const lines: string[] = [];

	for (const prop of properties) {
		const fullKey = prop.key;

		if (isObjectSchema(prop.schema) && prop.schema.properties) {
			const nestedProps = getSchemaProperties(prop.schema);
			const nestedLines = generateOptionsObject(nestedProps);
			lines.push(nestedLines);
			continue;
		}

		if (isArraySchema(prop.schema)) {
			const items = prop.schema.items;
			if (items && typeof items === "object" && !Array.isArray(items)) {
				const baseDesc = getSchemaTypeHint(items as JSONSchema7);
				if (prop.required) {
					lines.push(
						`    ${fullKey}: string("${fullKey}").desc("${baseDesc} (repeatable)"),`,
					);
				} else {
					// Arrays default to empty array (no default needed for repeatable options)
					lines.push(
						`    ${fullKey}: string("${fullKey}").desc("${baseDesc} (repeatable)"),`,
					);
				}
			}
			continue;
		}

		lines.push(`    ${fullKey}: ${generateOptionExpression(fullKey, prop)},`);
	}

	return lines.join("\n");
};


export const generateCLICode = (procedures: ProcedureInfo[]): string => {
	const project = new Project({
		useInMemoryFileSystem: true,
	});

	const sourceFile = project.createSourceFile("generated.ts");

	// Add leading comment
	sourceFile.insertText(0, "// Generated by orpc-cli - DO NOT EDIT\n\n");

	// Add imports
	sourceFile.addImportDeclaration({
		moduleSpecifier: "@drizzle-team/brocli",
		namedImports: ["command", "string", "number", "boolean"],
	});

	sourceFile.addImportDeclaration({
		moduleSpecifier: "fs",
		namespaceImport: "fs",
	});

	sourceFile.addImportDeclaration({
		moduleSpecifier: "path",
		namespaceImport: "path",
	});

	// Add helper function: getUniquePath
	sourceFile.addFunction({
		name: "getUniquePath",
		isExported: false,
		parameters: [{ name: "filePath", type: "string" }],
		returnType: "string",
		statements: `
	if (!fs.existsSync(filePath)) return filePath;
	
	const dir = path.dirname(filePath);
	const ext = path.extname(filePath);
	const base = path.basename(filePath, ext);
	
	let counter = 1;
	let newPath = filePath;
	while (fs.existsSync(newPath)) {
		newPath = path.join(dir, \`\${base}-\${counter}\${ext}\`);
		counter++;
	}
	return newPath;
	`,
	});

	// Add helper function: isAsyncIterable
	sourceFile.addFunction({
		name: "isAsyncIterable",
		isExported: false,
		parameters: [{ name: "value", type: "unknown" }],
		returnType: "boolean",
		statements: `
	return value !== null && 
		typeof value === 'object' && 
		typeof (value as AsyncIterable<unknown>)[Symbol.asyncIterator] === 'function';
	`,
	});

	// Add helper interface: FileMetadata
	sourceFile.addInterface({
		name: "FileMetadata",
		isExported: false,
		properties: [
			{ name: "path", type: "string" },
			{ name: "originalName", type: "string" },
			{ name: "contentType", type: "string" },
			{ name: "size", type: "number" },
		],
	});

	// Add helper function: saveFile
	sourceFile.addFunction({
		name: "saveFile",
		isExported: false,
		parameters: [
			{ name: "file", type: "File | Blob" },
			{ name: "outputDir", type: "string" },
		],
		returnType: "Promise<FileMetadata>",
		isAsync: true,
		statements: `
	const filename = file instanceof File ? file.name : \`download-\${Date.now()}\`;
	const buffer = Buffer.from(await file.arrayBuffer());
	const outputPath = path.resolve(outputDir, filename);
	
	const finalPath = getUniquePath(outputPath);
	
	fs.mkdirSync(path.dirname(finalPath), { recursive: true });
	fs.writeFileSync(finalPath, buffer);
	
	return {
		path: finalPath,
		originalName: filename,
		contentType: file.type || 'application/octet-stream',
		size: file.size,
	};
	`,
	});

	// Add processOutput helper function
	sourceFile.addFunction({
		name: "processOutput",
		isExported: false,
		parameters: [
			{ name: "result", type: "unknown" },
			{ name: "outputDir", type: "string", initializer: "'.'" },
		],
		returnType: "Promise<void>",
		isAsync: true,
		statements: `
	// Handle File/Blob responses - save to disk
	if (result instanceof File || result instanceof Blob) {
		const metadata = await saveFile(result, outputDir);
		console.log(JSON.stringify({ savedFiles: [metadata] }, null, 2));
		return;
	}
	
	// Handle object containing Files/Blobs
	if (result && typeof result === 'object' && !Array.isArray(result)) {
		const dataOutput: Record<string, unknown> = {};
		let hasFiles = false;
		
		for (const [key, value] of Object.entries(result)) {
			if (value instanceof File || value instanceof Blob) {
				const metadata = await saveFile(value, outputDir);
				dataOutput[key] = metadata;
				hasFiles = true;
			} else {
				dataOutput[key] = value;
			}
		}
		
		if (hasFiles) {
			console.log(JSON.stringify(dataOutput, null, 2));
			return;
		}
	}

	// Handle async iterator / SSE streaming
	if (isAsyncIterable(result)) {
		let index = 0;
		for await (const event of result as AsyncIterable<unknown>) {
			const timestamp = new Date().toISOString();
			console.log(\`[\${timestamp}] [\${++index}] \${JSON.stringify(event)}\`);
		}
		return;
	}

	// Regular output
	console.log(JSON.stringify(result, null, 2));
	`,
	});

	// Add handleError helper function
	sourceFile.addFunction({
		name: "handleError",
		isExported: false,
		parameters: [{ name: "error", type: "unknown" }],
		returnType: "never",
		statements: `
	const msg = error instanceof Error ? error.message : String(error);
	console.error(msg);
	process.exit(1);
	`,
	});

	// Create buildCommands as a variable
	sourceFile.addVariableStatement({
		declarationKind: VariableDeclarationKind.Const,
		declarations: [
			{
				name: "buildCommands",
				type: "(client: any) => any[]",
				initializer: (writer) => {
					writer.write("(client) => {");

					// Build command tree
					const tree = buildCommandTree(procedures);
					const topLevelVars: string[] = [];

					// Generate commands recursively
					const generateCommands = (
						node: CommandNode,
						varName: string,
						commandName: string,
						desc: string,
					): string => {
						if (node.type === "leaf") {
							const proc = node.procedure;
							const hasInput =
								proc.inputSchema?.properties &&
								Object.keys(proc.inputSchema.properties).length > 0;

							let optionsCode = "";
							if (hasInput) {
								const properties = getSchemaProperties(proc.inputSchema!);
								optionsCode = generateOptionsObject(properties);
							}

							const inputArg = hasInput ? "input" : "undefined";

							const outputOption = `output: string("output").alias("o").default(".").desc("Output directory for files"),`;
							const optionsWithOutput = optionsCode
								? `${optionsCode}\n${outputOption}`
								: outputOption;

							return `
  const ${varName} = command({
    name: "${commandName}",
    desc: "${desc}",
    options: {
${optionsWithOutput}
    },
    handler: async (opts) => {
      const { output, ...input } = opts;
      try {
        const result = await client.${proc.path}(${inputArg}, { context: { options: opts } });
        await processOutput(result, output);
      } catch (error) {
        handleError(error);
      }
    },
  });`;
						} else {
							const childVars: string[] = [];
							let childCode = "";

							for (const [childName, childNode] of node.children) {
								const childVarName = `${varName}_${childName}`;
								const childCommandName = childName;
								let childDesc: string;
								if (childNode.type === "leaf") {
									childDesc = childNode.procedure.path;
								} else {
									childDesc = `${childName} commands`;
								}

								childCode += generateCommands(
									childNode,
									childVarName,
									childCommandName,
									childDesc,
								);
								childVars.push(childVarName);
							}

							return `
${childCode}
  const ${varName} = command({
    name: "${commandName}",
    desc: "${desc}",
    subcommands: [${childVars.join(", ")}],
  });`;
						}
					};

					// Generate all top-level commands
					for (const [name, node] of tree) {
						const varName = name;
						let desc: string;
						if (node.type === "leaf") {
							desc = node.procedure.path;
						} else {
							desc = `${name} commands`;
						}

						writer.write(generateCommands(node, varName, name, desc));
						topLevelVars.push(varName);
					}

					// Return statement
					writer.write(`

  return [${topLevelVars.join(", ")}];
}`);
				},
			},
		],
		isExported: true,
	});

	sourceFile.addStatements(
		"\n// Optional: default export for convenience\nexport default buildCommands;",
	);

	return sourceFile.getFullText();
};
