/**
 * Code generation for CLI commands using ts-morph for type-safe AST generation
 */

import type { JSONSchema7 } from "json-schema";
import {
	Project,
	VariableDeclarationKind
} from "ts-morph";
import {
	getSchemaProperties,
	getSchemaTypeHint,
	isArraySchema,
	isObjectSchema,
} from "./introspect.js";
import type { ProcedureInfo, SchemaProperty } from "./types.js";

/**
 * Command tree node - can be a leaf (procedure) or a branch (group)
 */
type CommandNode =
	| { type: "leaf"; procedure: ProcedureInfo }
	| { type: "branch"; children: Map<string, CommandNode> };

/**
 * Build command tree recursively to support arbitrary nesting depth
 */
const buildCommandTree = (
	procedures: ProcedureInfo[],
): Map<string, CommandNode> => {
	const root = new Map<string, CommandNode>();

	for (const proc of procedures) {
		const segments = proc.path.split(".");
		let current = root;

		for (let i = 0; i < segments.length; i++) {
			const segment = segments[i];
			const isLast = i === segments.length - 1;

			if (isLast) {
				// Leaf node - the actual procedure
				current.set(segment, { type: "leaf", procedure: proc });
			} else {
				// Branch node - a command group
				if (!current.has(segment)) {
					current.set(segment, { type: "branch", children: new Map() });
				}

				// biome-ignore lint/style/noNonNullAssertion: Value is inserted above 
				const node = current.get(segment)!;
				if (node.type === "branch") {
					current = node.children;
				}
			}
		}
	}

	return root;
};

/**
 * Generate option builder expression for a schema property
 */
const generateOptionExpression = (
	key: string,
	prop: SchemaProperty,
): string => {
	const type = Array.isArray(prop.schema.type)
		? prop.schema.type[0]
		: prop.schema.type;
	const description = prop.schema.description || getSchemaTypeHint(prop.schema);

	let base: string;

	if (type === "number" || type === "integer") {
		base = `number("${key}").desc("${description}")`;
	} else if (type === "boolean") {
		base = `boolean("${key}").desc("${description}")`;
	} else if (prop.schema.enum && Array.isArray(prop.schema.enum)) {
		const enumValues = prop.schema.enum.map((v) => `"${v}"`).join(", ");
		base = `string("${key}").desc("${description}").enum(${enumValues})`;
	} else {
		base = `string("${key}").desc("${description}")`;
	}

	if (prop.defaultValue !== undefined) {
		// Output default value with proper type (no quotes for numbers and booleans)
		if (type === "number" || type === "integer") {
			return `${base}.default(${Number(prop.defaultValue)})`;
		} else if (type === "boolean") {
			return `${base}.default(${prop.defaultValue === true})`;
		} else {
			// strings and enums
			return `${base}.default("${String(prop.defaultValue)}")`;
		}
	}

	if (prop.required) {
		return `${base}.required()`;
	}

	return base;
};

/**
 * Generate options object for a procedure
 */
const generateOptionsObject = (properties: SchemaProperty[]): string => {
	const lines: string[] = [];

	for (const prop of properties) {
		const fullKey = prop.key;

		// Handle nested objects recursively
		if (isObjectSchema(prop.schema) && prop.schema.properties) {
			const nestedProps = getSchemaProperties(prop.schema);
			const nestedLines = generateOptionsObject(nestedProps);
			lines.push(nestedLines);
			continue;
		}

		// Handle arrays
		if (isArraySchema(prop.schema)) {
			const items = prop.schema.items;
			if (items && typeof items === "object" && !Array.isArray(items)) {
				const baseDesc = getSchemaTypeHint(items as JSONSchema7);
				if (prop.required) {
					lines.push(
						`    ${fullKey}: string("${fullKey}").desc("${baseDesc} (repeatable)"),`,
					);
				} else {
					// Arrays default to empty array (no default needed for repeatable options)
					lines.push(
						`    ${fullKey}: string("${fullKey}").desc("${baseDesc} (repeatable)"),`,
					);
				}
			}
			continue;
		}

		// Primitive
		lines.push(`    ${fullKey}: ${generateOptionExpression(fullKey, prop)},`);
	}

	return lines.join("\n");
};

/**
 * Generate the full CLI code using ts-morph
 */
export const generateCLICode = (
	procedures: ProcedureInfo[],
): string => {
	const project = new Project({
		useInMemoryFileSystem: true,
	});

	const sourceFile = project.createSourceFile("generated.ts");

	// Add leading comment
	sourceFile.insertText(0, "// Generated by orpc-cli - DO NOT EDIT\n\n");

	// Add import
	sourceFile.addImportDeclaration({
		moduleSpecifier: "@drizzle-team/brocli",
		namedImports: ["command", "string", "number", "boolean"],
	});

	// Add processOutput helper function
	sourceFile.addFunction({
		name: "processOutput",
		isExported: false,
		parameters: [{ name: "result", type: "unknown" }],
		returnType: "Promise<void>",
		isAsync: true,
		statements: `
	// Handle async iterator / SSE streaming
	if (result && typeof (result as AsyncIterable<unknown>)[Symbol.asyncIterator] === 'function') {
		let index = 0;
		for await (const event of result as AsyncIterable<unknown>) {
			const timestamp = new Date().toISOString();
			console.log(\`[\${timestamp}] [\${++index}] \${JSON.stringify(event)}\`);
		}
		return;
	}

	// Regular output
	console.log(JSON.stringify(result, null, 2));
	`,
	});

	// Add handleError helper function
	sourceFile.addFunction({
		name: "handleError",
		isExported: false,
		parameters: [{ name: "error", type: "unknown" }],
		returnType: "never",
		statements: `
	const msg = error instanceof Error ? error.message : String(error);
	console.error(msg);
	process.exit(1);
	`,
	});

	// Create buildCommands as a variable
	sourceFile.addVariableStatement({
		declarationKind: VariableDeclarationKind.Const,
		declarations: [
			{
				name: "buildCommands",
				type: "(client: any) => any[]",
				initializer: (writer) => {
					writer.write("(client) => {");

					// Build command tree
					const tree = buildCommandTree(procedures);
					const topLevelVars: string[] = [];

					// Generate commands recursively
					const generateCommands = (
						node: CommandNode,
						varName: string,
						commandName: string,
						desc: string,
					): string => {
						if (node.type === "leaf") {
							const proc = node.procedure;
							const hasInput =
								proc.inputSchema?.properties &&
								Object.keys(proc.inputSchema.properties).length > 0;

							let optionsCode = "";
							if (hasInput) {
								const properties = getSchemaProperties(proc.inputSchema!);
								optionsCode = generateOptionsObject(properties);
							}

							const inputArg = hasInput ? "input" : "undefined";

							return `
  const ${varName} = command({
    name: "${commandName}",
    desc: "${desc}",
    options: {
${optionsCode}
    },
    handler: async (opts) => {
      const { ...input } = opts;
      try {
        const result = await client.${proc.path}(${inputArg}, { context: { options: opts } });
        await processOutput(result);
      } catch (error) {
        handleError(error);
      }
    },
  });`;
						} else {
							// Branch node - generate subcommands recursively
							const childVars: string[] = [];
							let childCode = "";

							for (const [childName, childNode] of node.children) {
								const childVarName = `${varName}_${childName}`;
								const childCommandName = childName;
								let childDesc: string;
								if (childNode.type === "leaf") {
									childDesc = childNode.procedure.path;
								} else {
									childDesc = `${childName} commands`;
								}

								childCode += generateCommands(
									childNode,
									childVarName,
									childCommandName,
									childDesc,
								);
								childVars.push(childVarName);
							}

							return `
${childCode}
  const ${varName} = command({
    name: "${commandName}",
    desc: "${desc}",
    subcommands: [${childVars.join(", ")}],
  });`;
						}
					};

					// Generate all top-level commands
					for (const [name, node] of tree) {
						const varName = name;
						let desc: string;
						if (node.type === "leaf") {
							desc = node.procedure.path;
						} else {
							desc = `${name} commands`;
						}

						writer.write(generateCommands(node, varName, name, desc));
						topLevelVars.push(varName);
					}

					// Return statement
					writer.write(`

  return [${topLevelVars.join(", ")}];
}`);
				},
			},
		],
		isExported: true,
	});

	// Add default export
	sourceFile.addStatements(
		"\n// Optional: default export for convenience\nexport default buildCommands;",
	);

	// Return the generated code
	return sourceFile.getFullText();
};
