/**
 * Code generation for CLI commands using ts-morph for type-safe AST generation
 */

import {
	Project,
	SourceFile,
	VariableDeclarationKind,
	SyntaxKind,
} from "ts-morph";
import type { JSONSchema7 } from "json-schema";
import {
	getSchemaProperties,
	getSchemaTypeHint,
	isArraySchema,
	isObjectSchema,
} from "./introspect.js";
import type { ProcedureInfo, SchemaProperty } from "./types.js";

/**
 * Generate the handler function with output and SSE support
 */
const generateHandlerFunction = (
	fullPath: string,
	hasInput: boolean,
): string => {
	const inputArg = hasInput ? "input" : "undefined";

	return `async (opts) => {
  const { ...input } = opts;
  try {
    const result = await client.${fullPath}(${inputArg}, { context: { options: opts } });
    
    // Handle async iterator / SSE streaming
    if (result && typeof result[Symbol.asyncIterator] === 'function') {
      let index = 0;
      for await (const event of result) {
        const timestamp = new Date().toISOString();
        console.log(\`[\${timestamp}] [\${++index}] \${JSON.stringify(event)}\`);
      }
      return;
    }
    
    // Regular output
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error(msg);
    process.exit(1);
  }
}`;
};

/**
 * Generate option builder expression for a schema property
 */
const generateOptionExpression = (
	key: string,
	prop: SchemaProperty,
): string => {
	const type = Array.isArray(prop.schema.type)
		? prop.schema.type[0]
		: prop.schema.type;
	const description = prop.schema.description || getSchemaTypeHint(prop.schema);

	let base: string;

	if (type === "number" || type === "integer") {
		base = `number("${key}").desc("${description}")`;
	} else if (type === "boolean") {
		base = `boolean("${key}").desc("${description}")`;
	} else if (prop.schema.enum && Array.isArray(prop.schema.enum)) {
		const enumValues = prop.schema.enum.map((v) => `"${v}"`).join(", ");
		base = `string("${key}").desc("${description}").enum(${enumValues})`;
	} else {
		base = `string("${key}").desc("${description}")`;
	}

	if (prop.defaultValue !== undefined) {
		return `${base}.default("${String(prop.defaultValue)}")`;
	}

	if (prop.required) {
		return `${base}.required()`;
	}

	return base;
};

/**
 * Generate options object for a procedure
 */
const generateOptionsObject = (properties: SchemaProperty[]): string => {
	const lines: string[] = [];

	for (const prop of properties) {
		const fullKey = prop.key;

		// Handle nested objects recursively
		if (isObjectSchema(prop.schema) && prop.schema.properties) {
			const nestedProps = getSchemaProperties(prop.schema);
			const nestedLines = generateOptionsObject(nestedProps);
			lines.push(nestedLines);
			continue;
		}

		// Handle arrays
		if (isArraySchema(prop.schema)) {
			const items = prop.schema.items;
			if (items && typeof items === "object" && !Array.isArray(items)) {
				const baseDesc = getSchemaTypeHint(items as JSONSchema7);
				if (prop.required) {
					lines.push(
						`    ${fullKey}: string("${fullKey}").desc("${baseDesc} (repeatable)"),`,
					);
				} else {
					lines.push(
						`    ${fullKey}: string("${fullKey}").desc("${baseDesc} (repeatable)").default(""),`,
					);
				}
			}
			continue;
		}

		// Primitive
		lines.push(`    ${fullKey}: ${generateOptionExpression(fullKey, prop)},`);
	}

	return lines.join("\n");
};

/**
 * Build command tree recursively
 */
const buildCommandTree = (
	procedures: ProcedureInfo[],
	parentPath = "",
): {
	directCommands: ProcedureInfo[];
	groups: Map<string, ProcedureInfo[]>;
} => {
	const groups = new Map<string, ProcedureInfo[]>();
	const directCommands: ProcedureInfo[] = [];

	for (const proc of procedures) {
		const relativePath = parentPath
			? proc.path.slice(parentPath.length + 1)
			: proc.path;
		const segments = relativePath.split(".");

		if (segments.length === 1) {
			directCommands.push(proc);
		} else {
			const groupName = segments[0];
			if (!groups.has(groupName)) {
				groups.set(groupName, []);
			}
			groups.get(groupName)!.push(proc);
		}
	}

	return { directCommands, groups };
};

/**
 * Generate full CLI code using ts-morph
 */
export const generateCLICode = (
	procedures: ProcedureInfo[],
	config: { name: string; description?: string; version?: string },
): string => {
	const project = new Project({
		useInMemoryFileSystem: true,
		compilerOptions: {
			module: SyntaxKind.ESNextModule,
			target: SyntaxKind.ESNext,
		},
	});

	const sourceFile = project.createSourceFile("generated.ts");

	// Add leading comment
	sourceFile.insertText(0, "// Generated by orpc-cli - DO NOT EDIT\n\n");

	// Add import
	sourceFile.addImportDeclaration({
		moduleSpecifier: "@drizzle-team/brocli",
		namedImports: ["command", "string", "number", "boolean"],
	});

	// Create buildCommands as a variable instead of function
	sourceFile.addVariableStatement({
		declarationKind: VariableDeclarationKind.Const,
		declarations: [
			{
				name: "buildCommands",
				type: "(client: any) => any[]",
				initializer: (writer) => {
					writer.write("(client) => {");

					// Build command tree
					const { directCommands, groups } = buildCommandTree(procedures);
					const allTopLevel: string[] = [];

					// Generate leaf commands
					for (const proc of directCommands) {
						const varName = proc.path.replace(/\./g, "_");
						const commandName = proc.path;
						const hasInput =
							proc.inputSchema?.properties &&
							Object.keys(proc.inputSchema.properties).length > 0;

						let optionsCode = "";
						if (hasInput) {
							const properties = getSchemaProperties(proc.inputSchema!);
							optionsCode = generateOptionsObject(properties);
						}

						const handler = generateHandlerFunction(proc.path, hasInput);

						writer.write(`
  const ${varName} = command({
    name: "${commandName}",
    desc: "${proc.path}",
    options: {
${optionsCode}
    },
    handler: ${handler},
  });`);

						allTopLevel.push(varName);
					}

					// Generate group commands
					for (const [groupName, groupProcs] of groups) {
						const fullPath = groupName;
						const groupVarName = fullPath.replace(/\./g, "_");

						// Generate nested commands first
						for (const proc of groupProcs) {
							const varName = proc.path.replace(/\./g, "_");
							const nestedCommandName = proc.path.split(".").pop() || proc.path;
							const hasInput =
								proc.inputSchema?.properties &&
								Object.keys(proc.inputSchema.properties).length > 0;

							let optionsCode = "";
							if (hasInput) {
								const properties = getSchemaProperties(proc.inputSchema!);
								optionsCode = generateOptionsObject(properties);
							}

							const handler = generateHandlerFunction(proc.path, hasInput);

							writer.write(`
  const ${varName} = command({
    name: "${nestedCommandName}",
    desc: "${proc.path}",
    options: {
${optionsCode}
    },
    handler: ${handler},
  });`);
						}

						// Create group command
						const commandNames = groupProcs
							.map((p) => p.path.replace(/\./g, "_"))
							.join(", ");
						writer.write(`
  const ${groupVarName} = command({
    name: "${groupName}",
    desc: "${groupName} commands",
    subcommands: [${commandNames}],
  });`);

						allTopLevel.push(groupVarName);
					}

					// Return statement
					writer.write(`

  return [${allTopLevel.join(", ")}];
}`);
				},
			},
		],
		isExported: true,
	});

	// Add default export
	sourceFile.addStatements(
		"\n// Optional: default export for convenience\nexport default buildCommands;",
	);

	// Return the generated code
	return sourceFile.getFullText();
};
